load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

cc_library(
    name = "htime",
    srcs = ["htime.cc"],
    hdrs = ["htime.h"],
    visibility = ["//cmd:__pkg__"],
    deps = [
      "@fmt//:fmt",
    ],
)


